language: python
python:
  - "2.7"

# Use container-based infrastructure
sudo: false

# command to install dependencies
install:
  - which pip
  - pip --version
  - which python
  - python --version
  - pip install flake8 --upgrade
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m flake8 . || true
